[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"

[modules.rust.settings]
version = "1.98-slim-trixie"

[modules.wasm-pack]
source = "github.com/sagikazarmark/daggerverse-beta/wasm-pack"

[modules.wasm-pack.settings]
rustVersion = "1.98-slim-trixie"
defaultBrowsers = "CHROME"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

[modules.dang]
source = "github.com/sagikazarmark/daggerverse-beta/dang"
